unstable_features = true
use_small_heuristics = true
brace_style = "PreferSameLine"  # Default: "SameLineWhere"
max_width = 80  # Default: 100
format_strings = true  # Default: false
# report_todo = "Unnumbered"
# report_fixme = "Unnumbered"
struct_field_align_threshold = 20
use_try_shorthand = true
wrap_comments = true
# blank_lines_upper_bound = 2
